import BackHome from "@/app/components/BackHome"


export default function Page() {
  return (
    <div className='flex flex-col items-center min-h-screen p-24'>
      <div className="container p-6 mx-auto">
      <h1 className="mb-4 text-4xl font-bold">About LeetGPT</h1>

      <p className="mb-4 text-lg">
        LeetGPT is a powerful tool designed to assist you in solving LeetCode problems by providing hints and guidance.
      </p>

      <p className="mb-4 text-lg">
        Our goal is to make the process of tackling LeetCode problems more efficient and enjoyable. With LeetGPT, you can access generated hints that may give you insights and help you come up with innovative solutions.
      </p>

      <p className="mb-4 text-lg">
        LeetGPT leverages the OpenAI API to provide intelligent hints based on the problem description you provide. Please note that while the hints generated by LeetGPT are based on the capabilities of the OpenAI model, they may not always be perfect or optimal. We encourage you to use them as a reference and apply your own judgement in problem-solving.
      </p>

      <p className="mb-4 text-lg">
        Have questions, feedback, or suggestions? We'd love to hear from you! Feel free to reach out to us at <a href="mailto:contact@leetgpt.com" className="text-blue-500">contact@leetgpt.com</a>.
      </p>

      <p className="mb-4 text-lg">
        Happy coding and happy problem-solving with LeetGPT!
      </p>
    </div>
    <BackHome/>
    </div>
  )
}
